# Generated by Django 6.0.1 on 2026-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='сontent',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
